WebApplicationQL_TV/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;
using System.Web.Mvc;
using WebApplicationQL_TV.Model_new;
namespace WebApplicationQL_TV.Controllers
{
    public class DonHangController : Controller
    {
        // GET: DonHang
        public ActionResult ThongTinTatCaDonHang(int? page, string sortBy, string search)
        {
            Model2 db = new Model2();
            var query = "select HDM.maHoaDon ,HDM.maPhieuYeuCau,TrangThai,NgayMuonTra,TV.maThuVien," +
                "tenThuVien,TTV.maThe,maKH,tenKH,NV.maNV,DS.maDauSach,NV.tenNV,S.maSach,tenSach,soLuong " +
                "from HoaDonMuon HDM  inner join PhieuYeuCau PYC ON HDM.maPhieuYeuCau = PYC.maPhieuYeuCau " +
                "inner join ThuVien TV ON PYC.maThuVien = TV.maThuVien " +
                "inner join YeuCauMuon YCM ON YCM.maPhieuYeuCau = PYC.maPhieuYeuCau " +
                "inner join Sach S ON S.maSach = YCM.maSach " +
                "inner join TheThuVien TTV ON TTV.maThe = PYC.maThe " +
                "inner join KhachHang KH ON KH.maThe = TTV.maThe " +
                "inner join DauSach DS ON S.maDauSach = DS.maDauSach " +
                "inner join NhanVien NV ON NV.maNV = PYC.maNV ";
            var list = db.BangThongTinTatCaHoaDons.SqlQuery(query).ToList();
            if (search != null)
            {
                ViewBag.Current_search = search;
                query = query + " and maHoaDon like N'%" + search + "%'";
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query).ToList();
            }
            if (sortBy == "maHoaDon")
            {
                ViewBag.Current_sortBy = sortBy;
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query + " order by maHoaDon").ToList();
            }
            if (sortBy == "NgayMuon")
            {
                ViewBag.Current_sortBy = "NgayMuon";
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query + " order by NgayMuonTra ").ToList();
            }
            return View(list.ToPagedList(page ?? 1, 5));
        }
        public ActionResult ThongTinDonHangChuaTra(int? page, string sortBy, string search)
        {
            Model2 db = new Model2();
            var query = "select HDM.maHoaDon ,HDM.maPhieuYeuCau,TrangThai,NgayMuonTra,TV.maThuVien," +
                "tenThuVien,TTV.maThe,maKH,tenKH,NV.maNV,NV.tenNV,DS.maDauSach,S.maSach,tenSach,soLuong " +
                "from HoaDonMuon HDM  inner join PhieuYeuCau PYC ON HDM.maPhieuYeuCau = PYC.maPhieuYeuCau " +
                "inner join ThuVien TV ON PYC.maThuVien = TV.maThuVien " +
                "inner join YeuCauMuon YCM ON YCM.maPhieuYeuCau = PYC.maPhieuYeuCau " +
                "inner join Sach S ON S.maSach = YCM.maSach " +
                "inner join TheThuVien TTV ON TTV.maThe = PYC.maThe " +
                "inner join KhachHang KH ON KH.maThe = TTV.maThe " +
                "inner join DauSach DS ON S.maDauSach = DS.maDauSach " +
                "inner join NhanVien NV ON NV.maNV = PYC.maNV where TrangThai = 0";
            List<BangThongTinTatCaHoaDon> list = db.BangThongTinTatCaHoaDons.SqlQuery(query).ToList();
            if (search != null)
            {
                ViewBag.Current_search = search;
                query = query + " and maHoaDon like N'%"+search+"%'"; 
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query).ToList();
            }
            if (sortBy == "maHoaDon")
            {
                ViewBag.Current_sortBy = sortBy;
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query + " order by maHoaDon").ToList();
            }
            if (sortBy == "NgayMuon")
            {
                ViewBag.Current_sortBy = "NgayMuon";
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query + " order by NgayMuon ").ToList();
            }
            return View(list.ToPagedList(page ?? 1, 5));
        }
        public ActionResult ThongTinDonHangQuaHan(int? page ,string search,string sortBy)
        {
            Model2 db = new Model2();
            var query = "select HDM.maHoaDon ,HDM.maPhieuYeuCau,TrangThai,NgayMuonTra,TV.maThuVien," +
                "tenThuVien,TTV.maThe,maKH,tenKH,NV.maNV,DS.maDauSach,NV.tenNV,S.maSach,tenSach,soLuong " +
                "from HoaDonMuon HDM  inner join PhieuYeuCau PYC ON HDM.maPhieuYeuCau = PYC.maPhieuYeuCau " +
                "inner join ThuVien TV ON PYC.maThuVien = TV.maThuVien " +
                "inner join YeuCauMuon YCM ON YCM.maPhieuYeuCau = PYC.maPhieuYeuCau " +
                "inner join Sach S ON S.maSach = YCM.maSach " +
                "inner join TheThuVien TTV ON TTV.maThe = PYC.maThe " +
                "inner join KhachHang KH ON KH.maThe = TTV.maThe " +
                "inner join DauSach DS ON S.maDauSach = DS.maDauSach " +
                "inner join NhanVien NV ON NV.maNV = PYC.maNV where TrangThai = 0 and DateDiff(month,NgayMuonTra,getDate()) > 8";
            var list = db.BangThongTinTatCaHoaDons.SqlQuery(query).ToList();
            if (search != null)
            {
                ViewBag.Current_search = search;
                query = query + " and maHoaDon like N'%" + search + "%'";
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query).ToList();
            }
            if (sortBy == "maHoaDon")
            {
                ViewBag.Current_sortBy = sortBy;
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query + " order by maHoaDon").ToList();
            }
            if (sortBy == "NgayMuon")
            {
                ViewBag.Current_sortBy = "NgayMuon";
                list = db.BangThongTinTatCaHoaDons.SqlQuery(query + " order by NgayMuon ").ToList();
            }
            return View(list.ToPagedList(page ?? 1,5));
        }
        public ActionResult Create(string id)
        {
            return View();
        }
        [HttpPost ,ActionName("Create")]
        public ActionResult CreateConfirm(BangThongTinTatCaHoaDon thongTinHoaDon)
        {
            Model2 db = new Model2();
            
            var obj_Found = db.PhieuYeuCaus.Find(thongTinHoaDon.maPhieuYeuCau);
            if (obj_Found != null) return Redirect("Create");
            var obj_Found_1 = db.Saches.Find(thongTinHoaDon.maSach);
            if (obj_Found_1 == null) return Redirect("Create");
            var obj_Found_2 = db.TheThuViens.Find(thongTinHoaDon.maThe);
            if (obj_Found_2 == null) return Redirect("Create");
            var obj_Found_3 = db.NhanViens.Find(thongTinHoaDon.maNV);
            if (obj_Found_3 == null) return Redirect("Create");
            var obj_Found_4 = db.HoaDonMuons.Find(thongTinHoaDon.maHoaDon);
            if (obj_Found_4 != null) return Redirect("Create");
            var obj_Found_5 = db.TheThuViens.Find(thongTinHoaDon.maThuVien);
            if (obj_Found_5 != null) return Redirect("Create");

            db.Database.ExecuteSqlCommand("insert into PhieuYeuCau(maPhieuYeuCau,maThe,maNV,maThuVien) " +
                "values ( '" + thongTinHoaDon.maPhieuYeuCau + "' ,'" + thongTinHoaDon.maThe + "','"
                + thongTinHoaDon.maNV + "','" + thongTinHoaDon.maThuVien + "')");
            db.Database.ExecuteSqlCommand("insert into YeuCauMuon(maSach, maPhieuYeuCau ,soLuong) " +
                "values ('"+ thongTinHoaDon.maSach+"' ,'"+ thongTinHoaDon.maPhieuYeuCau +"' " +
                ", '" + thongTinHoaDon.soLuong +"')");
            var TrangThai1 = 0;

            if (thongTinHoaDon.TrangThai == true)  TrangThai1 = 1;
            else TrangThai1 = 0;

            db.Database.ExecuteSqlCommand("insert into HoaDonMuon(maPhieuYeuCau,maHoaDon,TrangThai,ngayMuonTra) " +
                "values ('"+ thongTinHoaDon.maPhieuYeuCau + "','"+ thongTinHoaDon.maHoaDon + "','"+TrangThai1+"','"+ thongTinHoaDon.NgayMuonTra + "')");
            db.SaveChanges();
            return RedirectToAction("ThongTinTatCaDonHang");
        }
        public ActionResult Delete(string id)
        {
            Model2 db = new Model2();
            var query = "select HDM.maHoaDon ,HDM.maPhieuYeuCau,TrangThai,NgayMuonTra,TV.maThuVien," +
                "tenThuVien,TTV.maThe,maKH,tenKH,NV.maNV,DS.maDauSach,NV.tenNV,S.maSach,tenSach,soLuong " +
                "from HoaDonMuon HDM  inner join PhieuYeuCau PYC ON HDM.maPhieuYeuCau = PYC.maPhieuYeuCau " +
                "inner join ThuVien TV ON PYC.maThuVien = TV.maThuVien " +
                "inner join YeuCauMuon YCM ON YCM.maPhieuYeuCau = PYC.maPhieuYeuCau " +
                "inner join Sach S ON S.maSach = YCM.maSach " +
                "inner join TheThuVien TTV ON TTV.maThe = PYC.maThe " +
                "inner join KhachHang KH ON KH.maThe = TTV.maThe " +
                "inner join DauSach DS ON S.maDauSach = DS.maDauSach " +
                "inner join NhanVien NV ON NV.maNV = PYC.maNV where maHoaDon = '"+id+"'";
            var DonHang_Found = db.BangThongTinTatCaHoaDons.SqlQuery(query).SingleOrDefault();
            return View(DonHang_Found);
        }
        [HttpPost,ActionName("Delete")]
        public ActionResult DeleteConfirm(string id)
        {
            Model2 db = new Model2();
            var DonHang_Found = db.HoaDonMuons
                .SqlQuery("select * from HoaDonMuon where TrangThai = 1 " +
                " and maHoaDon = '" + id + "'").SingleOrDefault();
            if (DonHang_Found == null) return RedirectToAction("Delete");
            else
            {
                HoaDonMuon maPhieuYeuCau_delete = db.HoaDonMuons.SqlQuery("select * from HoaDonMuon where maHoaDon = '"+id+"'").SingleOrDefault();
                db.Database.ExecuteSqlCommand("delete from YeuCauMuon where " +
                    " maPhieuYeuCau in (select maPhieuYeuCau from PhieuYeuCau where " +
                    " maPhieuYeuCau in ( select maPhieuYeuCau from HoaDonMuon where maHoaDon = " +
                    "'"+id+"'))");
                

WebApplicationQL_TV/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationQL_TV.Models;
namespace WebApplicationQL_TV.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

WebApplicationQL_TV/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WebApplicationQL_TV.Model_new;
using PagedList.Mvc;

namespace WebApplicationQL_TV.Controllers
{
    public class SachController : Controller
    {
        // GET: Sach
        public ActionResult ThongTinSach(string sortBy,string search,int? page)
        {
            if (sortBy != null) ViewBag.Current_sortBy = sortBy;
            else sortBy = ViewBag.Current_sortBy;
            if (search != null) ViewBag.Current_search = search;
            else search = ViewBag.Current_search;
            
            Model2 db = new Model2();
            var query = "Select * from Sach";
            var list = db.Saches.SqlQuery(query).ToList();
            if(search != null )
            {
                query = query + " where maSach = '"+search+"'";
                list = db.Saches.SqlQuery(query).ToList();
            }
            if(sortBy == "maSach")
            {
                query = query + " order by maSach";
                list = db.Saches.SqlQuery(query).ToList();
            }
            if (sortBy == "tenSach")
            {
                query = query + " order by tenSach";
                list = db.Saches.SqlQuery(query).ToList();
            }
            return View(list.ToPagedList(page ?? 1,5));
        }
        
        public ActionResult Create()
        {
            return View();
        }
       
        public ActionResult ThongTinSachDangMuon(int? page)
        {
            Model2 db = new Model2();
            string query = "select * from Sach where "
                +"maSach not in (select maSach from YeuCauMuon) or maSach in"
                +" (select maSach from YeuCauMuon where maPhieuYeuCau in "
                +" (select maPhieuYeuCau where maPhieuYeuCau in " 
                +"(select maPhieuYeuCau from HoaDonMuon where TrangThai=1)))";
            var list = db.Saches.SqlQuery(query).ToList();
            return View(list.ToPagedList(page ?? 1, 5));
        }
        public ActionResult Details(string id)
        {
            if (id == null) return RedirectToAction("ThongTinSach");
            Model2 db = new Model2();
            Sach sach_have_been_found = db.Saches.Find(id);
            return View(sach_have_been_found);
        }
        
        public ActionResult Edit(string id)
        {
            if (id == null) return RedirectToAction("ThongTinSach"); 
            Model2 db = new Model2();
            Sach sach = db.Saches.Find(id);
            return View(sach);
        }
        public ActionResult Delete(string id)
        {
            if (id == null) return RedirectToAction("ThongTinSach");
            Model2 db = new Model2();
            Sach sach = db.Saches.Find(id);
            return View(sach);
        }
        public ActionResult BangSach()
        {
            Model2 db = new Model2();
            var list = db.Saches.SqlQuery("exec BangSach").ToList();
            return View(list);
        }
        [HttpPost, ActionName("Create")]
        public ActionResult CreateConFirm(Sach sach)
        {
            Model2 db = new Model2();
            var sach_finder = db.Saches.Find(sach.maSach);
            if (sach_finder != null)
            {
                db.Saches.Add(sach_finder);
                db.SaveChanges();
                return RedirectToAction("ThongTinSach");
            }
            else
            {
                db.Saches.Add(sach);
                db.SaveChanges();
                return RedirectToAction("ThongTinSach");
            }
            
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            Model2 db = new Model2();
            Sach delete_sach = db.Saches.SqlQuery("select * from Sach where ( maSach in " +
                "(select maSach from YeuCauMuon where maPhieuYeuCau in " +
                "(select maPhieuYeuCau from PhieuYeuCau where maPhieuYeuCau in " +
                "(select maPhieuYeuCau from HoaDonMuon where trangThai = 1))) " +
                " and maSach = '"+id+ "') " +
                "OR (maSach not in (select maSach from YeuCauMuon) " +
                "and maSach = '"+id+ "')").SingleOrDefault();
            if (delete_sach == null) return RedirectToAction("ThongTinSach");
            else
            {
                db.Database.ExecuteSqlCommand("delete from Sach where maSach = '"+id+"'");
                db.SaveChanges();
            }
            return RedirectToAction("ThongTinSach");
        }
        [HttpPost, ActionName("Edit")]
        public ActionResult Edit(Sach sach)
        {
            Model2 db = new Model2();
            Sach editor_Sach = db.Saches.Find(sach.maSach);
            editor_Sach.ghiChu = sach.ghiChu;
            editor_Sach.maLoaiSach = sach.maLoaiSach;
            if (TryUpdateModel(editor_Sach))
            {
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("ThongTinSach");
                }
                catch
                {
                    return RedirectToAction("ThongTinSach");
                }
            }
            return RedirectToAction("ThongTinSach");
        }
    }
}

WebApplicationQL_TV/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div>
    Thực Tập Cơ Sở Dữ Liệu Nhóm 9
</div>

WebApplicationQL_TV/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div><h1> Quản Lý Thư Viện </h1></div>
<div>
    <ul class="list-group">
        <h2>Quản Lý Sách </h2>
        <li>
            @Html.ActionLink("Quản Lý Tất Cả Thông Tin Sách", "ThongTinSach", "Sach")
        </li>
        <li>
            @Html.ActionLink("Quản Lý Sách Chưa Được Mượn", "ThongTinSachDangMuon", "Sach")
        </li>
    </ul>
    <ul class="list-group">
        <h2>Quản Lý Đầu Sách </h2>
        <li>
            @Html.ActionLink("Quản Lý Tất Cả Thông Tin Đầu Sách", "TatCaDauSachVaSach", "DauSachVaSach")
        </li>
    </ul>
    <ul class="list-group">
        <h2>Quản Lý Hóa Đơn</h2>
        <li>
            @Html.ActionLink("Quản Lý Tất Cả Hóa Đơn", "ThongTinTatCaDonHang", "DonHang")
        </li>
        <li>
            @Html.ActionLink("Quản Lý Tất Cả Hóa Đơn Chưa trả", "ThongTinDonHangChuaTra", "DonHang")
        </li>
        <li>
            @Html.ActionLink("Quản Lý Tất Cả Hóa Đơn Chưa Trả và Đã Quá Hạn", "ThongTinDonHangQuaHan", "DonHang")
        </li>
    </ul>
    <ul class="list-group">
        <h2>Quản Lý Nhân Viên</h2>
    </ul>
    <li>
        @Html.ActionLink("Quản Lý Tất Cả Nhân Viên", "ThongTinNhanVien", "NhanVien")
    </li>
    <li>
        @Html.ActionLink("Quản Lý Tất Cả Nhân Viên Thuộc Bộ Phận 001", "ThongTinNhanVienThuocBoPhan001", "NhanVien")
    </li>
    <li>
        @Html.ActionLink("Quản Lý Tất Cả Nhân Viên Thuộc Bộ Phận 003", "ThongTinNhanVienThuocBoPhan003", "NhanVien")
    </li>
    <li>
        @Html.ActionLink("Quản Lý Tất Cả Nhân Viên Thuộc Bộ Phận 001", "ThongTinNhanVienThuocBoPhan001", "NhanVien")
    </li>
    <li>
        @Html.ActionLink("Quản Lý Tất Cả Nhân Viên Chưa Viết Đơn Hàng ", "ThongTinNhanVienChuaVietDonHang", "NhanVien")
    </li>
</div>

WebApplicationQL_TV/Views/Home/dsdasdad.cshtml
@model IEnumerable<WebApplicationQL_TV.Models.Sach>

@{
    ViewBag.Title = "dsdasdad";
}

<h2>dsdasdad</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LoaiSach.tenLoaiSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NgonNgu.ngonNgu1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhaXuatBan.tenNhaXuatBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TacGia.tenTacGia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.soTrang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.namXuatBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.giaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ghiChu)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiSach.tenLoaiSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgonNgu.ngonNgu1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhaXuatBan.tenNhaXuatBan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TacGia.tenTacGia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tenSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.soTrang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.namXuatBan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.giaSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ghiChu)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.maSach }) |
            @Html.ActionLink("Details", "Details", new { id=item.maSach }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.maSach })
        </td>
    </tr>
}

</table>