WebApplicationQL_TV/Controllers/DauSachVaSachController.cs
using PagedList;
using System.Linq;
using System.Web.Mvc;
using WebApplicationQL_TV.Model_new;

namespace WebApplicationQL_TV.Controllers
{
    public class DauSachVaSachController : Controller
    {
        Model2 db = new Model2();
        // GET: DauSachVaSach
        public ActionResult TatCaDauSachVaSach(int? page, string sortBy, string search)
        {
            Model2 db = new Model2();

            var query = "SELECT DS.maDauSach,tenDauSach,maTacGia,maNgonNgu" +
                ",maNhaXuatBan,S.maSach,S.tenSach,S.soTrang,S.namXuatBan,S.giaSach" +
                ",S.ghiChu,S.maLoaiSach,S.maKhoSach from Sach S inner join DauSach DS ON " +
                " DS.maDauSach = S.maDauSach ";
            if (search != null)
            {
                ViewBag.Current_search = search;
                query = query + " where DS.maDauSach like '%" + search + "%'";
            }
            if (sortBy == "maDauSach")
            {
                ViewBag.Current_sortBy = sortBy;
                query = query + " order by DS.maDauSach";
            }
            if (sortBy == "tenDauSach")
            {
                ViewBag.Current_sortBy = sortBy;
                query = query + " order by DS.tenDauSach";
            }
            var list = db.BangDauSachVaSaches.SqlQuery(query).ToList();
            return View(list.ToPagedList(page ?? 1, 5));
        }
        public ActionResult BangDauSach(int ? page,string sortBy ,string search)
        {
            var query = "select * from DauSach";
            if (search != null)
            {
                ViewBag.Current_search = search;
                query = query + " where DS.maDauSach like '%" + search + "%'";
            }
            if (sortBy == "maDauSach")
            {
                ViewBag.Current_sortBy = sortBy;
                query = query + " order by DS.maDauSach";
            }
            if (sortBy == "tenDauSach")
            {
                ViewBag.Current_sortBy = sortBy;
                query = query + " order by DS.tenDauSach";
            }
            var list = db.DauSaches.SqlQuery(query).ToList();
            return View(list.ToPagedList(page ?? 1,5));
        }
        public ActionResult Details(string id)
        {
            var query = "Select * from DauSach where maDauSach = '" + id + "'";
            var obj_found = db.DauSaches.SqlQuery(query).SingleOrDefault();
            return View(obj_found);
        }
        public ActionResult Edit(string id)
        {
            var query = "Select * from DauSach where maDauSach = '" + id + "'";
            var obj_found = db.DauSaches.SqlQuery(query).SingleOrDefault();
            return View(obj_found);
        }
        [HttpPost, ActionName("Edit")]
        public ActionResult Edit(DauSach obj)
        {
            var statment1 = db.TacGias.SqlQuery("select * from TacGia where maTacGia = '" + obj.maTacGia + "'").SingleOrDefault();
            var statment2 = db.NhaXuatBans.SqlQuery("select * from NhaXuatBan where maNhaXuatBan = '" + obj.maNhaXuatBan + "'").SingleOrDefault();
            var statment3 = db.NgonNgus.SqlQuery("select maNgonNgu,NgonNgu,ghiChu from NgonNgu WHERE maNgonNgu = '" + obj.maNgonNgu + "'").SingleOrDefault();
            if (statment1 != null && statment2 != null && statment3 != null)
            {
                var query = "update DauSach set maTacGia = '" + obj.maTacGia + "' ," +
                    "maNgonNgu = '" + obj.maNgonNgu + "',maNhaXuatBan = '" + obj.maNhaXuatBan + "' " +
                    " ,tenDauSach = '" + obj.tenDauSach + "' where maDauSach = '" + obj.maDauSach + "'";
                db.Database.ExecuteSqlCommand(query);
                db.SaveChanges();
                return RedirectToAction("TatCaDauSachVaSach");
            }
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost, ActionName("Create")]
        public ActionResult Create(DauSach obj)
        {

            var statment1 = db.TacGias.SqlQuery("select * from TacGia where maTacGia = '" + obj.maTacGia + "'").SingleOrDefault();
            var statment2 = db.NhaXuatBans.SqlQuery("select * from NhaXuatBan where maNhaXuatBan = '" + obj.maNhaXuatBan + "'").SingleOrDefault();
            var statment4 = db.DauSaches.SqlQuery("select * from DauSach where maDauSach = '" + obj.maDauSach + "'").SingleOrDefault();
            var statment3 = db.NgonNgus.SqlQuery("select * from NgonNgu WHERE maNgonNgu = '" + obj.maNgonNgu + "'").SingleOrDefault();
            
            if (statment1 != null && statment2 != null && statment3 != null)
            {
                if (statment4 == null)
                {
                    var query = "insert into DauSach(maDauSach,tenDauSach,maTacGia,maNgonNgu,maNhaXuatBan) values('" + obj.maDauSach + "','" + obj.tenDauSach + "','" + obj.maTacGia + "','" + obj.maNgonNgu + "','" + obj.maNhaXuatBan + "')";
                    db.Database.ExecuteSqlCommand(query);
                    db.SaveChanges();
                    return RedirectToAction("TatCaDauSachVaSach");
                }
            }
            return View();

        }
        public ActionResult Delete(string id)
        {
            var query = "Select * from DauSach where maDauSach = '" + id + "'";
            var obj_found = db.DauSaches.SqlQuery(query).SingleOrDefault();
            return View(obj_found);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteComfirm(string id)
        {
            var query = "SELECT DS.maDauSach,tenDauSach,maTacGia,maNgonNgu" +
                ",maNhaXuatBan,S.maSach,S.tenSach,S.soTrang,S.namXuatBan,S.giaSach" +
                ",S.ghiChu,S.maLoaiSach,S.maKhoSach from Sach S inner join DauSach DS ON " +
                " DS.maDauSach = S.maDauSach where DS.maDauSach = '"+id+"'";
            var obj_found = db.BangDauSachVaSaches.SqlQuery(query).SingleOrDefault();
            if(obj_found == null) {
                db.Database.ExecuteSqlCommand("delete DauSach where maDauSach = '"+id+"'");
                db.SaveChanges();
                return RedirectToAction("TatCaDauSachVaSach");
            }
            return View();
        }
    }
}

WebApplicationQL_TV/Views/DauSachVaSach/BangDauSach.cshtml
@model IPagedList<WebApplicationQL_TV.Model_new.DauSach>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "BangDauSach";
}

<h2>BangDauSach</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("BangDauSach", "DauSachVaSach", FormMethod.Get))
{
    <tr>Tìm Kiếm Theo Mã Dau Saches : </tr>
    <input type="text" name="search" value="@ViewBag.Current_search" />
    <tr>Sắp Xếp Theo : </tr>
    <select name="sortBy">
        <option value="@ViewBag.Current_sortBy">@ViewBag.Current_sortBy</option>
        <option value="maDauSach">maDauSach</option>
        <option value="tenDauSach">tenDauSach</option>
    </select>
    <input class="btn btn-default" type="submit" value="Tìm Kiếm" />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().maDauSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maNgonNgu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maNhaXuatBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maTacGia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().tenDauSach)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.maDauSach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.maNgonNgu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.maNhaXuatBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.maTacGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tenDauSach)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.maDauSach }) |
                @Html.ActionLink("Details", "Details", new { id = item.maDauSach }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.maDauSach })
            </td>
        </tr>
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("BangDauSach", "DauSachVaSach", new { page, sortBy = ViewBag.Current_sortBy, search = ViewBag.Current_search }))

WebApplicationQL_TV/Views/DauSachVaSach/Create.cshtml
@model WebApplicationQL_TV.Model_new.DauSach

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DauSach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.maDauSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maDauSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maDauSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tenDauSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenDauSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenDauSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maTacGia, "maTacGia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maTacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maTacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maNgonNgu, "maNgonNgu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maNgonNgu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maNgonNgu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maNhaXuatBan, "maNhaXuatBan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maNhaXuatBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maNhaXuatBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplicationQL_TV/Views/DauSachVaSach/Delete.cshtml
@model WebApplicationQL_TV.Model_new.DauSach

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DauSach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NgonNgu.ngonNgu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgonNgu.ngonNgu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaXuatBan.tenNhaXuatBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.tenNhaXuatBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TacGia.tenTacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TacGia.tenTacGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tenDauSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenDauSach)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" onclick="return confirm('Are you sure you want to delete ?')"   /> 
        </div>
    }
</div>

WebApplicationQL_TV/Views/DauSachVaSach/Details.cshtml
@model WebApplicationQL_TV.Model_new.DauSach

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DauSach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NgonNgu.ngonNgu1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgonNgu.ngonNgu1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaXuatBan.tenNhaXuatBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.tenNhaXuatBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TacGia.tenTacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TacGia.tenTacGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tenDauSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenDauSach)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.maDauSach })
</p>

WebApplicationQL_TV/Views/DauSachVaSach/Edit.cshtml
@model WebApplicationQL_TV.Model_new.DauSach

@{
    ViewBag.Title = "Edit";
}
@using WebApplicationQL_TV.Model_new;
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DauSach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.maDauSach)

        <div class="form-group">
            @Html.LabelFor(model => model.tenDauSach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenDauSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenDauSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maTacGia, "maTacGia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maTacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maTacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maNgonNgu, "maNgonNgu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maNgonNgu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maNgonNgu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maNhaXuatBan, "maNhaXuatBan", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maNhaXuatBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maNhaXuatBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplicationQL_TV/Views/DauSachVaSach/TatCaDauSachVaSach.cshtml
@model IPagedList<WebApplicationQL_TV.Model_new.BangDauSachVaSach>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "TatCaDauSachVaSach";
}

<h2>TatCaDauSachVaSach</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("TatCaDauSachVaSach", "DauSachVaSach", FormMethod.Get))
{
    <tr>Tìm Kiếm Theo Mã Dau Saches : </tr>
    <input type="text" name="search" value="@ViewBag.Current_search" />
    <tr>Sắp Xếp Theo : </tr>
    <select name="sortBy">
        <option value="@ViewBag.Current_sortBy">@ViewBag.Current_sortBy</option>
        <option value="maDauSach">maDauSach</option>
        <option value="tenDauSach">tenDauSach</option>
    </select>
    <input class="btn btn-default" type="submit" value="Tìm Kiếm" />
}
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().maDauSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().tenDauSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maTacGia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maNgonNgu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maNhaXuatBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().tenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().soTrang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().namXuatBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().giaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().ghiChu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maLoaiSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().maKhoSach)
        </th>
        <th>
            Các Chức Năng
        </th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.maDauSach)
    </td>

   
    <td>
        @Html.DisplayFor(modelItem => item.tenDauSach)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.maTacGia)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.maNgonNgu)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.maNhaXuatBan)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.maSach)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.tenSach)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.soTrang)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.namXuatBan)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.giaSach)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ghiChu)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.maLoaiSach)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.maKhoSach)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.maDauSach }) |
        @Html.ActionLink("Details", "Details", new { id = item.maDauSach }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.maDauSach })
    </td>
</tr>
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("TatCaDauSachVaSach", "DauSachVaSach", new { page, sortBy = ViewBag.Current_sortBy, search = ViewBag.Current_search }))